name: my_dvm_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_core_platform_interface: ^4.5.1
  flutter_custom_switch: ^0.0.3
  flutter_switch: ^0.3.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: null
  intl_phone_field: ^3.1.0
  otp_text_field: ^1.1.3
  pinput: ^2.2.16
  platform: null
  platform_plus: ^2.0.15
  provider: ^6.0.4
  razorpay_flutter: ^1.3.2
  shared_preferences: ^2.0.15
  toggle_switch: ^2.0.1
  get_storage: ^2.0.3
  dio: ^4.0.6
  fluttertoast: ^8.1.2
  flutter_keyboard_visibility: ^5.4.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  build_context: ^3.0.0
  custom_switch: ^0.0.1
  
  
flutter_test:
    sdk: flutter

flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/image.jpg
    - assets/images/dvm.png
    - assets/images/gps.png
    - assets/images/map.png
    - assets/images/home.png
    - assets/images/check.png
    - assets/images/clear.png
    - assets/images/circle.png
    